[project]
name = "shidsbot"
requires-python = ">=3.9"
version = "0.1.0"
dependencies = [
    "discord.py[voice]==2.2.2",
    "python-dotenv==0.21.0",
    "yt-dlp==2023.2.17",
    "httpx==0.23.3",
    "tabulate==0.9.0"
]
